### ISSUE TITLE
Is IO itself Open Source?

### ISSUE THREAD

**Issue by probonopd** [adafruit/io-api#1]
Is the code for adafruit.io itself Open Source, i.e., could I run my own instance of IO including the Web interface?

**Comment by ReanimationXP** [comment]
I'm wondering the same.

**Comment by jwcooper** [comment]
In addition to all of our open sourced client libraries, we have an open source self-hosted server located here: https://github.com/adafruit/adafruit-io-node

It does not have all of the features of the hosted IO, but should allow you to download your data and self-host on your own system to avoid any lock-in. We try to do our best to keep that up to date with the hosted io, but it can get out of sync. We accept pull requests for any updates required on that as well.

The hosted io server code and infrastructure has a lot of moving parts that would be very difficult to properly open source and support so it is not something we plan on doing at this time.
